DROP DATABASE IF EXISTS blogs_db;
CREATE DATABASE blogs_db;

CREATE TABLE Users (
    Username VARCHAR(30) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Pass PASSWORD
)

CREATE TABLE Posts (
    Title VARCHAR(30) NOT NULL,
    Body MEDIUMTEXT NOT NULL
)

USE blogs_db;